"""add chat_messages table

Revision ID: 487e2ebbbbed
Revises: 2961eb6c6dc4
Create Date: 2026-07-26 10:54:06.698970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487e2ebbbbed'
down_revision = '2961eb6c6dc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
