"""add role column to users

Revision ID: 519e751f05d1
Revises: e9272215d819
Create Date: 2026-08-04 09:41:48.533304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519e751f05d1'
down_revision = 'e9272215d819'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
