"""add behavioral_insights table

Revision ID: 755b5de78d09
Revises: bebc595a2690
Create Date: 2026-07-20 17:12:17.461311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '755b5de78d09'
down_revision = 'bebc595a2690'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('pattern_label', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_insights_id'), 'behavioral_insights', ['id'], unique=False)
    op.create_index(op.f('ix_behavioral_insights_insight_type'), 'behavioral_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_behavioral_insights_user_id'), 'behavioral_insights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavioral_insights_user_id'), table_name='behavioral_insights')
    op.drop_index(op.f('ix_behavioral_insights_insight_type'), table_name='behavioral_insights')
    op.drop_index(op.f('ix_behavioral_insights_id'), table_name='behavioral_insights')
    op.drop_table('behavioral_insights')
    # ### end Alembic commands ###
