"""update activity log

Revision ID: bebc595a2690
Revises: 20260709_monitoring
Create Date: 2026-07-13 22:38:52.625466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebc595a2690'
down_revision = '20260709_monitoring'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('device', sa.String(length=100), nullable=True))
    op.add_column('activity_logs', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('activity_logs', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('activity_logs', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'status')
    op.drop_column('activity_logs', 'ip_address')
    op.drop_column('activity_logs', 'browser')
    op.drop_column('activity_logs', 'device')
    # ### end Alembic commands ###
