"""add website to organizations

Revision ID: dffb33273a0e
Revises: 519e751f05d1
Create Date: 2026-08-07 03:30:17.070628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffb33273a0e'
down_revision = '519e751f05d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'website')
    # ### end Alembic commands ###
